services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
