name: spacemate-backoffice
services:
  - build_command: pnpm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: false
      repo: spacemateio/spacemate-backoffice
    name: spacemate-backoffice
