import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GeneralProvider from "@/utils/GeneralProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SpaceMateIO",
  description: "Generated by SpaceMateIO",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <GeneralProvider>{children}</GeneralProvider>
      </body>
    </html>
  );
}
